#+title: Config
#+author: H. Hernan Saez

* Table of Contents :toc:
- [[#introduction][Introduction]]
- [[#user-setup][User Setup]]
- [[#editor][Editor]]
- [[#os-specific][OS Specific]]
  - [[#mac-os-x][Mac OS X]]
  - [[#window-wsl][Window WSL]]
- [[#frame-setup][Frame Setup]]
- [[#fonts][Fonts]]
- [[#theme][Theme]]
- [[#dashboard][Dashboard]]
- [[#misc][Misc]]
- [[#development][Development]]
  - [[#compilation][Compilation]]
  - [[#projectile][Projectile]]
  - [[#treemacs][Treemacs]]
  - [[#tree-sitter-grammars][Tree-sitter grammars]]
- [[#gpt-el][GPT-EL]]

* Introduction
Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!


* User Setup
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets. It is optional.

#+BEGIN_SRC emacs-lisp
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")
#+END_SRC

* Editor

Disable empty line markers

#+BEGIN_SRC emacs-lisp
(setq-default indicate-empty-lines nil)

(after! vi-tilde-fringe
  (global-vi-tilde-fringe-mode -1))
(remove-hook 'prog-mode-hook #'vi-tilde-fringe-mode)
#+END_SRC

Use the Command key as Meta on macOS while leaving Option for accented characters.

#+BEGIN_SRC emacs-lisp
(when (eq system-type 'darwin)
  (setq mac-command-modifier 'meta
        mac-option-modifier 'none
        ns-command-modifier 'meta
        ns-option-modifier 'none))
#+END_SRC

Revert buffers when the underlying file has changed.

#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode 1)
#+END_SRC

By default Emacs will close all windows when pressing the ESC key. I hate that.

Instead, map the ESC key to keyboard-escape-quit (C-g) instead

#+BEGIN_SRC emacs-lisp
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))
#+END_SRC

In addition, this seems to make the minibuffer to exit with just one ESC key press (instead of ESC ESC ESC by default)

Skip the confirmation prompt when quitting with =C-x C-c= unless processes are still running (keep that warning).

#+BEGIN_SRC emacs-lisp
(setq confirm-kill-emacs nil
      confirm-kill-processes t)
#+END_SRC

* OS Specific

** Mac OS X

Restore the default macOS font zoom shortcuts now that Command behaves as Meta.

#+BEGIN_SRC emacs-lisp
(when (eq system-type 'darwin)
  (map! "M-=" #'doom/increase-font-size
        "M-+" #'doom/increase-font-size
        "M--" #'doom/decrease-font-size
        "M-_" #'doom/decrease-font-size
        "M-0" #'doom/reset-font-size))
#+END_SRC

** Window WSL

#+BEGIN_SRC emacs-lisp
(defun hhsaez/wsl-p ()
  (and (eq system-type 'gnu/linux)
       (or (getenv "WSL_INTEROP")
           (file-exists-p "/proc/sys/fs/binfmt_misc/WSLInterop"))))

(defun hhsaez/apply-borderless-frame ()
  (when (hhsaez/wsl-p)
    (dolist (param '((undecorated . t)
                     (drag-internal-border . 10)
                     (internal-border-width . 10)
                     (alpha-background . 100)))
      (setf (alist-get (car param) default-frame-alist) (cdr param))
      (add-to-list 'initial-frame-alist param))))

(add-hook 'after-init-hook #'hhsaez/apply-borderless-frame)

 (defun hhsaez/toggle-undecorated-frame ()
    "Toggle window-manager decorations on the current frame."
    (interactive)
    (let* ((frame (selected-frame))
           (current (frame-parameter frame 'undecorated)))
      (set-frame-parameter frame 'undecorated (not current))))
#+END_SRC

* Frame Setup
#+BEGIN_SRC emacs-lisp
(setq frame-resize-pixelwise t
      window-resize-pixelwise t)

(defvar hhsaez/frame-state-file
  (expand-file-name "frame-state.el" doom-cache-dir)
  "File used to persist the last GUI frame size and position.")

(defun hhsaez/save-frame-state ()
  "Persist the current GUI frame size and position."
  (when (display-graphic-p)
    (let* ((frame (selected-frame))
           (pos (frame-position frame))
           (left (car pos))
           (top (cdr pos))
           (width (frame-pixel-width frame))
           (height (frame-pixel-height frame)))
      (when (and (numberp left) (numberp top)
                 (numberp width) (numberp height))
        (with-temp-file hhsaez/frame-state-file
          (prin1 (list :left left :top top :width width :height height)
                 (current-buffer)))))))

(defun hhsaez/restore-frame-state (&optional frame)
  "Restore FRAME size and position from `hhsaez/frame-state-file`."
  (let ((frame (or frame (selected-frame))))
    (when (and (display-graphic-p frame)
               (file-exists-p hhsaez/frame-state-file))
      (with-temp-buffer
        (insert-file-contents hhsaez/frame-state-file)
        (let* ((data (read (current-buffer)))
               (left (plist-get data :left))
               (top (plist-get data :top))
               (width (plist-get data :width))
               (height (plist-get data :height)))
          (when (and (numberp left) (numberp top)
                     (numberp width) (numberp height))
            (set-frame-size frame width height t)
            (set-frame-position frame left top)
            t))))))

(defun hhsaez/scale-and-center-frame (&optional frame)
  "Resize FRAME to 80%x90% of its monitor and center it. Works for new frames too."
  (let* ((frame (or frame (selected-frame))))
    (when (and (display-graphic-p frame)
               (fboundp 'frame-monitor-attributes)
               (not (hhsaez/restore-frame-state frame)))
      (let* ((attrs (frame-monitor-attributes frame))
             (workarea (alist-get 'workarea attrs)))
        (when (and workarea (>= (length workarea) 4))
          (pcase-let* ((`(,wx ,wy ,ww ,wh) workarea)
                       (frame-width (floor (* ww 0.8)))
                       (frame-height (floor (* wh 0.9)))
                       (left (+ wx (/ (- ww frame-width) 2)))
                       (top (+ wy (/ (- wh frame-height) 2))))
            (set-frame-size frame frame-width frame-height t)
            (set-frame-position frame (round left) (round top))))))))

(add-hook 'after-init-hook #'hhsaez/scale-and-center-frame t)
(add-hook 'after-make-frame-functions #'hhsaez/scale-and-center-frame)
(add-hook 'kill-emacs-hook #'hhsaez/save-frame-state)
#+END_SRC

* Fonts
Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.
- `doom-symbol-font' -- for symbols
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they accept. For example:

#+BEGIN_SRC emacs-lisp
;;n(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
(setq doom-font (font-spec :family "JetBrains Mono" :size 16)
      doom-symbol-font (font-spec :family "Noto Sans Symbols" :size 16))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!
#+END_SRC

* Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one)
#+END_SRC

* Dashboard

#+BEGIN_SRC emacs-lisp
(setq +doom-dashboard-banner-file (concat doom-user-dir "wallpaper.png"))
#+END_SRC

* Misc
#+BEGIN_SRC emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+END_SRC

* Development

The following allos code blocks within .org files to be formatted when using /C-c '/

#+BEGIN_SRC emacs-lisp

;; Good Org src defaults (indent inside blocks with c++-mode rules)
(after! org
  (setq org-src-tab-acts-natively t
        org-src-preserve-indentation nil
        org-edit-src-content-indentation 0)

  (setq org-src-window-setup 'other-window)

  (defun hhsaez/org-src-display-buffer (buffer alist)
    (if (>= (window-total-width) 160)
        (display-buffer-in-direction
         buffer
         (append alist '((direction . right)
                         (window-width . 0.5))))
      (display-buffer-at-bottom buffer alist)))

  (add-to-list 'display-buffer-alist
               '("^\\*Org Src" hhsaez/org-src-display-buffer)))

;; Make org-src C++ edit buffers format like .cpp, without clang-format
(after! org-src
  (defun my/org-src-cpp-lsp-format-setup ()
    (when (and (bound-and-true-p org-src-mode)
               (derived-mode-p 'c++-mode))
      ;; give buffer a plausible filename/dir so clangd attaches (you already did this)
      (unless buffer-file-name
        (setq-local buffer-file-name
                    (expand-file-name "org-src-edit.cpp" default-directory)))

      ;; ensure LSP is running
      (when (fboundp 'lsp-deferred) (lsp-deferred))

      ;; 1) Format on save (optional)
      (add-hook 'before-save-hook #'lsp-format-buffer nil t)

      ;; 2) Use TAB to format (instead of cc-mode indent) in the edit buffer
      (local-set-key (kbd "TAB") #'lsp-format-buffer)

      ;; If you still want cc-mode indent on Shift+TAB:
      (local-set-key (kbd "<backtab>") #'indent-for-tab-command)

      ;; If you want to try on-type formatting anyway:
      ;; (setq-local lsp-enable-on-type-formatting t)
      ;; Note: may be limited or interfered by electric-indent-mode.
      ))
  (add-hook 'org-src-mode-hook #'my/org-src-cpp-lsp-format-setup))
#+END_SRC

Ensure regular C++ buffers behave the same way: run clangd on save and when pressing TAB.

#+BEGIN_SRC emacs-lisp
;; Keep C++ buffers in sync with clang-format defaults (indent, save hooks, TAB formatting).
(after! cc-mode
  ;; Only format when LSP is initialized; otherwise saving a new buffer errors out.
  (defun hhsaez/lsp-format-buffer-if-ready ()
    (when (and (bound-and-true-p lsp-mode)
               (fboundp 'lsp-format-buffer))
      (lsp-format-buffer)))

  ;; Prefer LSP formatting for TAB, but gracefully fall back to cc-mode indent.
  (defun hhsaez/lsp-format-or-indent ()
    (interactive)
    (if (and (bound-and-true-p lsp-mode)
             (fboundp 'lsp-format-buffer))
        (lsp-format-buffer)
      (indent-for-tab-command)))

  (require 'seq)

  ;; Look up the closest readable .clang-format, preferring the projectile root.
  (defun hhsaez/clang-format-find-config ()
    (let* ((project-file (when (and (fboundp 'projectile-project-root)
                                    (projectile-project-root))
                           (expand-file-name ".clang-format" (projectile-project-root))))
           (local-dir (or (and buffer-file-name
                               (locate-dominating-file buffer-file-name ".clang-format"))
                          (locate-dominating-file default-directory ".clang-format")))
           (local-file (when local-dir (expand-file-name ".clang-format" local-dir))))
      (seq-find #'file-readable-p (delq nil (list project-file local-file)))))

  ;; Pull numeric settings (IndentWidth, etc.) straight from the config file.
  (defun hhsaez/clang-format-extract-number (key)
    (when-let ((file (hhsaez/clang-format-find-config)))
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (when (re-search-forward (format "^%s:\\s-*\\([0-9]+\\)" (regexp-quote key)) nil t)
          (string-to-number (match-string 1))))))

  ;; Apply clang-format's indent width so typing matches formatter output.
  (defun hhsaez/c++-apply-indent-width ()
    (when-let ((indent (hhsaez/clang-format-extract-number "IndentWidth")))
      (setq-local c-basic-offset indent
                  tab-width indent)
      (when (boundp 'c-ts-mode-indent-offset)
        (setq-local c-ts-mode-indent-offset indent))))

  ;; Main entry point: set indentation, hook formatting on save, and bind keys.
  (defun hhsaez/c++-lsp-format-setup ()
    (hhsaez/c++-apply-indent-width)
    (add-hook 'before-save-hook #'hhsaez/lsp-format-buffer-if-ready nil t)
    (local-set-key (kbd "TAB") #'hhsaez/lsp-format-or-indent)
    (local-set-key (kbd "<backtab>") #'indent-for-tab-command))

  (dolist (hook '(c++-mode-hook c++-ts-mode-hook))
    (add-hook hook #'hhsaez/c++-lsp-format-setup)))
#+END_SRC

** Compilation
Keep compilation buffers (including projectile builds) scrolled to the newest output. Show them at the bottom by default, with a toggle to move them to the left when needed.

#+BEGIN_SRC emacs-lisp
(after! compile
  (setq compilation-scroll-output t)

  (defvar hhsaez/compilation-popup-side 'bottom
    "Preferred side for displaying compilation popups.")

  (defun hhsaez/apply-compilation-popup-rule (&optional side)
    "Apply the compilation popup rule using SIDE or `hhsaez/compilation-popup-side'."
    (let ((side (or side hhsaez/compilation-popup-side)))
      (set-popup-rule! "^\\*compilation\\*"
        :side side
        :size 0.25)))

  (defun hhsaez/toggle-compilation-popup-side ()
    "Toggle the compilation popup between the bottom and the left."
    (interactive)
    (setq hhsaez/compilation-popup-side
          (if (eq hhsaez/compilation-popup-side 'bottom)
              'left
            'bottom))
    (hhsaez/apply-compilation-popup-rule)
    (let ((buf (get-buffer "*compilation*")))
      (when buf
        (display-buffer buf)))
    (message "Compilation popup side: %s" hhsaez/compilation-popup-side))

  (hhsaez/apply-compilation-popup-rule)

  (defun my/next-error-prioritize-errors (orig-fn &rest args)
    "Prefer diagnostics with severity ≥ error when cycling with `next-error'."
    (let ((orig-threshold compilation-skip-threshold))
      (condition-case _err
          (let ((compilation-skip-threshold (max 2 (or compilation-skip-threshold 0)))
                (inhibit-message t)
                (ring-bell-function #'ignore))
            (apply orig-fn args))
        (user-error
         (let ((compilation-skip-threshold orig-threshold))
           (apply orig-fn args))))))

  (unless (advice-member-p #'my/next-error-prioritize-errors 'next-error)
    (advice-add 'next-error :around #'my/next-error-prioritize-errors))

  (defun hhsaez/compilation-reuse-visible-window (orig-fn msg mk &optional other-window)
    "Show compile errors in a visible buffer/window when one already exists."
    (let* ((target (marker-buffer mk))
           (reuse-window (and target (get-buffer-window target 0))))
      (cond
       (reuse-window
        (select-window reuse-window)
        (funcall orig-fn msg mk nil))
       ((and (derived-mode-p 'compilation-mode)
             (not other-window)
             (not (one-window-p t)))
        (funcall orig-fn msg mk t))
       (t
        (funcall orig-fn msg mk other-window)))))

  (unless (advice-member-p #'hhsaez/compilation-reuse-visible-window 'compilation-goto-locus)
    (advice-add 'compilation-goto-locus :around #'hhsaez/compilation-reuse-visible-window)))
#+END_SRC

** Projectile
Treat git submodules as part of the parent project instead of switching roots. The helper below asks git for the superproject directory; if we are inside a submodule it returns the top-level checkout so projectile keeps that as the active project. When no superproject exists the fallback still lets projectile use its usual detection.

#+BEGIN_SRC emacs-lisp
(after! projectile
  (require 'subr-x)
  (defun my/projectile-root-superproject (dir)
    "Return the superproject root for DIR when inside a git submodule."
    (when dir
      (let ((default-directory dir))
        (let* ((raw (when (executable-find "git")
                      (ignore-errors
                        (car (process-lines "git" "rev-parse" "--show-superproject-working-tree")))))
               (raw (and raw (string-trim raw)))
               (candidate (cond
                           ((and raw (not (string-empty-p raw)))
                            (if (file-name-absolute-p raw)
                                raw
                              (expand-file-name raw)))
                           (t (locate-dominating-file dir ".gitmodules"))))
               (resolved (and candidate
                              (file-name-as-directory (expand-file-name candidate)))))
          (when (and resolved (not (string-suffix-p "/" resolved)))
            (setq resolved (concat resolved "/")))
          (when (and resolved
                     (not (string-equal (directory-file-name resolved)
                                        (directory-file-name (expand-file-name dir)))))
            resolved)))))
  (add-to-list 'projectile-project-root-functions #'my/projectile-root-superproject))
#+END_SRC

** Codex CLI
Run the Codex CLI from the current Projectile project without leaving Emacs.

#+BEGIN_SRC emacs-lisp
(after! projectile
  (defun hhsaez/codex-run ()
    "Launch the Codex CLI in a real terminal at the Projectile project root."
    (interactive)
    (let ((root (projectile-project-root)))
      (unless root
        (user-error "Not inside a Projectile project"))
      (let* ((default-directory root)
             (codex (or (executable-find "codex")
                        (user-error "Codex executable not found in PATH")))
             (buffer-name (generate-new-buffer-name "*Codex*")))
        (require 'term)
        (let ((term-buffer (make-term buffer-name codex)))
          (with-current-buffer term-buffer
            (term-mode)
            (term-char-mode))
          (pop-to-buffer term-buffer))))))
#+END_SRC

** CMake
Ensure the cmake language server can be installed even when the Python package manager is only exposed as =pip3= or via =python -m pip=.

#+BEGIN_SRC emacs-lisp
(after! lsp-cmake
  (require 'subr-x)
  (require 'cl-lib)

  (defvar hhsaez/lsp-cmake-pip-packages
    '("pygls<2" "cmake-language-server==0.1.11")
    "Package specs installed whenever cmakels is bootstrapped.")

  (defun hhsaez/lsp-cmake--python-user-base ()
    (when-let ((python (or (executable-find "python3")
                           (executable-find "python"))))
      (ignore-errors
        (string-trim
         (car (process-lines python "-m" "site" "--user-base"))))))

  (defun hhsaez/lsp-cmake--user-bin-paths ()
    (let* ((home (or (getenv "HOME") default-directory))
           (base (hhsaez/lsp-cmake--python-user-base))
           (paths (delq nil
                        (list (when base (expand-file-name "bin" base))
                              (expand-file-name ".local/bin" home)))))
      (append (file-expand-wildcards (expand-file-name "Library/Python/*/bin" home))
              paths)))

  (defun hhsaez/lsp-cmake-ensure-user-path ()
    (dolist (bin (cl-remove-duplicates (hhsaez/lsp-cmake--user-bin-paths) :test #'string-equal))
      (when (file-directory-p bin)
        (unless (member bin exec-path)
          (push bin exec-path))
        (let ((path (getenv "PATH")))
          (unless (and path (string-match (regexp-quote bin) path))
            (setenv "PATH" (if path (concat bin path-separator path) bin)))))))

  (hhsaez/lsp-cmake-ensure-user-path)

  (defun hhsaez/lsp-cmake--pip-command ()
    (cond ((executable-find "pip3") '("pip3"))
          ((executable-find "pip") '("pip"))
          ((executable-find "python3") '("python3" "-m" "pip"))
          ((executable-find "python") '("python" "-m" "pip"))))

  (defun hhsaez/lsp-cmake-download-server (_client callback error-callback update?)
    (let ((cmd (hhsaez/lsp-cmake--pip-command)))
      (if cmd
          (let* ((program (car cmd))
                 (args (cdr cmd))
                 (process-environment (cons "PIP_BREAK_SYSTEM_PACKAGES=1" process-environment)))
            (apply #'lsp-async-start-process
                   callback
                   error-callback
                   program
                   (append args
                           (list "install" "--user")
                           (when update? '("-U"))
                           hhsaez/lsp-cmake-pip-packages)))
        (funcall error-callback
                 "No pip executable found. Install Python's pip so cmake-language-server can be fetched."))))

  (advice-add 'lsp-cmake--download-server :override #'hhsaez/lsp-cmake-download-server))
#+END_SRC

** Treemacs

#+BEGIN_SRC emacs-lisp
(after! treemacs
  (setq treemacs-is-never-other-window nil))
#+END_SRC

** Tree-sitter grammars
Install missing C/C++ grammars automatically so tree-sitter works on fresh setups.

#+BEGIN_SRC emacs-lisp
(after! treesit
  (require 'cl-lib)
  (defvar hhsaez/treesit-auto-grammars '(c cpp)
    "Tree-sitter grammars that must be present locally.")

  (defvar hhsaez/treesit-language-sources
    '((c . ("https://github.com/tree-sitter/tree-sitter-c"))
      (cpp . ("https://github.com/tree-sitter/tree-sitter-cpp")))
    "Alist of LANG . SOURCE tuples to ensure before installing grammars.")

  ;; Guarantee treesit knows how to fetch our required grammars.
  (dolist (entry hhsaez/treesit-language-sources)
    (cl-pushnew entry treesit-language-source-alist
                :test (lambda (a b) (eq (car a) (car b)))))

  (defun hhsaez/ensure-treesit-grammars (&optional languages)
    "Install any missing tree-sitter LANGUAGES without prompting."
    (when (and (fboundp 'treesit-install-language-grammar)
               (fboundp 'treesit-language-available-p))
      (dolist (lang (or languages hhsaez/treesit-auto-grammars))
        (unless (treesit-language-available-p lang)
          (condition-case err
              (progn
                (message "Installing tree-sitter grammar for %s..." lang)
                (treesit-install-language-grammar lang))
            (error
             (message "tree-sitter grammar install failed for %s: %s" lang err)))))))

  (hhsaez/ensure-treesit-grammars))
#+END_SRC

* GPT-EL

#+BEGIN_SRC emacs-lisp
(after! gptel
  (require 'gptel-gh)
  (setq gptel-backend
        (gptel-make-gh-copilot "copilot-chat")
        gptel-model 'gpt-4o))
#+END_SRC
